#!/bin/bash

for file in `find . -name '*_data.txt' -o -name '*_sample.txt'`
do
  outfile=`echo $file | sed s/.txt/.pl/`
  term=data
  if [[ $file =~ sample ]] ; then term=sample ; fi
  printf ":- set_prolog_flag(double_quotes, chars).\n$term([%s])." "$(cat $file | xargs -I{} printf "\"%s\",\n" "{}")" | sed s/,]/]/ > $outfile
done