#!/bin/bash

if [ "$1" == "-r" ]
then
  days=$(find . -name '*.pl' -exec grep -l begin_tests {} \; | sort)
  for day in $days
  do
    dirname=$(dirname $day)
    pushd $dirname >/dev/null
    swipl -g 'time(run_tests)' -t halt $(basename $day)
    popd >/dev/null
  done
else
  f=`grep -l begin_tests *.pl`
  if [ -z "$f" ]
  then
    echo "No prolog tests found!"
    exit 1
  fi
  
  swipl -g 'time(run_tests)' -t halt $f
fi
